language: go

go:
    - 1.5

os:
    - linux
    - osx
    - windows

install:
    - go get -t -v ./...

script:
    - go build -v
    - go test ./...


notifications:
    email:
        - aldo@corte.si
